rogerclarkmelbourne/OpenGD77

firmware/source/fw_main.c

Pressing e.g. KEY_RIGHT in dmr channel mode while backlight is off changes the talkgroup and turns backlight on.
I think it's better to only turn on backlight and discard the key event. 
The next keypress does the actual change.
And it is possible to turn on the backlight to look at the display by pressing any key.

If key is pressed while backlight is off, turn backlight on and discard key

---

firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/uiVFOMode.c

Also allows in VFO mode to enter frequency and omit trailing zeros with key green, e.g. 145,5.

Display rx and tx frequency in channel details screen. #47

---

firmware/source/hardware/UC1701.c

Check if char to be rendered is inside font boundary.
BTW, I'm in the font ATM, and is there a reason to have ASCII 127 (DEL) support ?

Font boundary checking.

---

firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiUtilityQSOData.c
firmware/source/user_interface/uiVFOMode.c

Hi,
This morning I was experiencing some garbage rendered, while listening TG91/3100, just bellow TG xxx, where contact/talker alias should be printed.
Checking the code I find few locations where "string" buffer could be overflowed or non NULL terminated.
Cheers.

Prevent buffer overlow, and insure strings are NULL terminated before rendered on LCD screen.

---

firmware/source/user_interface/menuNumericalEntry.c

In DMR mode added entry 'Contact' to key HASH.
Select one contact stored in codeplug with LEFT or RIGHT and use it as PC or TG override.
The TG contacts are included as not all TG's need to be in the RX-list used for the active channel.
Perhaps we should add an alias for TG override. So the name of the contact instead of the ID is shown in uiVFOMode and uiChannelMode.

Access contacts in DMR mode for PC or TG entry

---

firmware/source/user_interface/uiUtilityQSOData.c

Fixes #70
If the radio is in narrowband, both receive and transmit tones are set,
and power is set to less than 1W, the `CTR` will be right next to the power.
`FM N CTR250mW`

Add `N` after `FM` when using 12.5kHz FM

---

firmware/include/hardware/UC1701.h
firmware/include/hardware/UC1701_charset.h
firmware/source/fw_main.c
firmware/source/hardware/UC1701.c
firmware/source/user_interface/menuFirmwareInfoScreen.c
firmware/source/user_interface/menuLastHeard.c
firmware/source/user_interface/menuRSSIScreen.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiHotspot.c
firmware/source/user_interface/uiLockScreen.c
firmware/source/user_interface/uiPowerOff.c
firmware/source/user_interface/uiSplashScreen.c
firmware/source/user_interface/uiTxScreen.c
firmware/source/user_interface/uiTxTgPcContactOwnId.c
firmware/source/user_interface/uiUtilityQSOData.c
firmware/source/user_interface/uiVFOMode.c

Major change is the following (+ functions prototype):
#define UC1701_FONT_6X8 				0
#define UC1701_FONT_6X8_bold			1
#define UC1701_FONT_8X8 				2
#define UC1701_FONT_GD77_8x16 			3
#define UC1701_FONT_16x32 				4
typedef enum
{
UC1701_FONT_6x8 = 0,
UC1701_FONT_6x8_BOLD,
UC1701_FONT_8x8,
UC1701_FONT_8x16,
UC1701_FONT_16x32
} UC1701_Font_t;
Also, it renames font font_gd77_8x16  to font_8x16[].
Cheers.

Cleanup and hamonize font types and identifiers, create UC1701_Font_t enum type instead of #defines.

---

firmware/.cproject
firmware/source/user_interface/menuFirmwareInfoScreen.c

Hi Roger,
Here is the modification to display git hash. I think that could prevent confusion when someone reports a build date from a firmware *not officially* built. 
At least, with the hash, it could be clear if the user is using the latest build.
This has been tested under Linux and Windows.
Cheers.

Git hash in info

---

firmware/include/functions/fw_ticks.h
firmware/include/hardware/UC1701.h
firmware/source/functions/fw_ticks.c
firmware/source/hardware/UC1701.c
firmware/source/user_interface/uiTxTgPcContactOwnId.c

Add blinking cursor when numerical value is expected (taking account of the CCS7 lenght).
Add fw_millis(void) function.
I think it's nicer.

Add drop-shadow box around TG/PC/Contact/DMR-ID menu title.

---

firmware/include/user_interface/menuSystem.h
firmware/source/user_interface/menuContactDetails.c
firmware/source/user_interface/menuContactList.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/uiInfoMsgScreen.c

1. If a new private contact is created and the ID is found in the DMR ID database that info is used as the contact name instead of 'PC #######'. The text from the DMR ID is shorten to 16 letters.
2. Deleting a contact is added to the 'Contact List'
Deleting a private contact is done by pressing SK2+RED.
TG's can not be deleted right now. I will add this later for TG's not used in a RX Group.

Add delete contact to 'Contact List', use DMR ID as name in 'New Contact'

---

firmware/source/user_interface/uiVFOMode.c

The first time I tried to switch between VFO A and B I was confused
because I'm use to the ":" indicating that I modify the value with Left
or Right. This makes this menu item consistent with others controlled in
the same way.

Display "VFO:B" instead of "VFO B" in quick menu

---

firmware/source/fw_main.c
firmware/source/user_interface/uiLockScreen.c

This is a partially fix, as I couldn't produce the crash as described.
But I got a crash when PTT was locked and then unlocked.
I changed the key handling in uiLockScreen.c. So maybe it fixed the other problems.

Fix crash when unlocking PTT lock

---

firmware/include/io/fw_keyboard.h
firmware/source/fw_main.c
firmware/source/io/fw_keyboard.c
firmware/source/user_interface/menuBattery.c
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/menuContactDetails.c
firmware/source/user_interface/menuContactList.c
firmware/source/user_interface/menuCredits.c
firmware/source/user_interface/menuDisplayMenuList.c
firmware/source/user_interface/menuDisplayOptions.c
firmware/source/user_interface/menuLanguage.c
firmware/source/user_interface/menuLastHeard.c
firmware/source/user_interface/menuMessageScreen.c
firmware/source/user_interface/menuOptions.c
firmware/source/user_interface/menuRSSIScreen.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/menuZoneList.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiHotspot.c
firmware/source/user_interface/uiTxTgPcContactOwnId.c
firmware/source/user_interface/uiUtilityQSOData.c
firmware/source/user_interface/uiVFOMode.c

- Remove workaround from fw_main, as not needed anymore.
- Change keycodes. This will enable us in the future to implement input of letters in fw_keyboard
- Fix a crash in Zone menu, when UP or DOWN is repeating.

Some keypad additions

---

firmware/include/functions/fw_codeplug.h
firmware/source/functions/fw_codeplug.c
firmware/source/user_interface/menuContactDetails.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiVFOMode.c

If a TG or PC is entered manual and a contact with that ID exists, the contact name is displayed instead of the ID.
For private calls if no contact exists the dmr id data is used.
If a override TG or PC is set, a border is drawn around the ID or name.

Manual TG or PC displays contact name if available.

---

firmware/source/user_interface/menuSystem.c

Checking if new root menu is MENU_MAIN_MENU in menuSystemPopAllAndDisplaySpecificRootMenu(), as it should display [1] instead of [0].

---

firmware/include/user_interface/menuSystem.h
firmware/source/functions/fw_codeplug.c
firmware/source/user_interface/menuLanguage.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/uiChannelMode.c

Fix a bug when using All_Channels and switching language, everything is messed up. Now, menuChannelMode() is forced to do a cold start if language has changed.

Fix a buffer overflow when using All_Channels zone.

---

firmware/include/user_interface/menuSystem.h
firmware/include/user_interface/menuUtilityQSOData.h
firmware/source/fw_main.c
firmware/source/user_interface/menuBattery.c
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/menuContactDetails.c
firmware/source/user_interface/menuContactList.c
firmware/source/user_interface/menuCredits.c
firmware/source/user_interface/menuDisplayMenuList.c
firmware/source/user_interface/menuDisplayOptions.c
firmware/source/user_interface/menuFirmwareInfoScreen.c
firmware/source/user_interface/menuLanguage.c
firmware/source/user_interface/menuLastHeard.c
firmware/source/user_interface/menuMessageScreen.c
firmware/source/user_interface/menuOptions.c
firmware/source/user_interface/menuRSSIScreen.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/menuZoneList.c
firmware/source/user_interface/uiCPS.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiHotspot.c
firmware/source/user_interface/uiLockScreen.c
firmware/source/user_interface/uiPowerOff.c
firmware/source/user_interface/uiSplashScreen.c
firmware/source/user_interface/uiTxScreen.c
firmware/source/user_interface/uiTxTgPcContactOwnId.c
firmware/source/user_interface/uiUtilityQSOData.c
firmware/source/user_interface/uiVFOMode.c

This struct also embeds a tick counter, issued from fw_millis().
The boolean member hasEvent is true if the current key/button/event is different from the previous sent event.
handleEvent() is only called if necessary.
Removed: int menuTimer, int RssiUpdateCounter. Timeout is calc from ui_event_t.ticks instead.

Change menuFunction()s and handleEvent() prototypes, use a new ui_event_t struct to propagate the events.

---

firmware/source/fw_main.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiVFOMode.c

Clear squelch region if still displayed while PTT is triggered.

Cleanup uiEvent_t.hasEvent checking code in main loop.

---

firmware/source/user_interface/uiUtilityQSOData.c

If the caller ID is not the same as the trxTalkGroupOrPcId and the
received ID is the radios DMR ID, the 'Accept private call' message is
displayed. Otherwise only 'private call' is displayed. Fixes #205
BTW: Shouldn't be calls to use the reflectors on Brandmeister private calls not TGs? So e.g. PC 5000 to check connected reflectors.

Incoming private calls are displayed as ID: ### instead of TG: ###.

---

firmware/source/fw_main.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/uiLockScreen.c

Hide lockscreen on key/button event (button events is quite hard to handle, so if the lockscreen pops up on button press event, it will be hidden on button release).
Call menuSystemPopPreviousMenu() on PTT event if lockscreen is running (as it will be redisplayed after a short PTT event).
Also (I forgot to mention in commit's comment), stack offset is checked in menuSystemPopPreviousMenu(), preventing reboots if called more than necessary.

Fix hidden lockscreen on keypad locking.

---

firmware/source/functions/fw_trx.c

Initial selection of Rx Preamp was based on Tx frequency. Should be Rx Frequency.
Affected crossband operation.

Correct Rx Preamp Initial Selection

---

.gitattributes
.gitignore

I've also added a gitignore entry for extracted fonts in font_tools/font_converter/ subdir.

Add .gitattributes, and force eol to lf (to avoid crlf mergings).

---

firmware/source/user_interface/uiChannelMode.c

but only when QSO_DISPLAY_CALLER_DATA comes up. Wakeup backlight on user key event.
That prevents the backlight to kicks in when switching to RX, with nothing more.

Do not wakeup the backlight when someone stops talking,

---

firmware/source/user_interface/uiVFOMode.c

Fix two backlight triggering bugs.
The Y misalignment is here on purpose.
Cheers.
**EDIT:**
There is also inverted version (not pushed until further notice):

Display VFO A or B (see screengrabs).

---

firmware/include/user_interface/menuUtilityQSOData.h
firmware/source/user_interface/uiUtilityQSOData.c
firmware/source/user_interface/uiVFOMode.c

and all infos are moved down by one row. Tx info is hidden.
Any user key event stops the scan (as before), and screen redrawn with default layout.
The scrambled header line is due to scanning while screen grabbing.
This PR may conflit with the one related to VFO A/B changes.

While CC scan is running, "Color Code #" is displayed at Contact location, 

---

firmware/source/fw_main.c

Since menuVFOModeIsScanning() exists, use it.

Before TXing, check if VFO is scanning before blindly stopping it.

---

firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/menuSystem.c

Add 's' unit to TOT.
Shift editing cursor to 1px on the right, it was misaligned with the character above.

When displaying channel details within VFO, instead of an empty channel name, mark it as N/A.

---

firmware/.cproject
firmware/include/fw_main.h
firmware/linkerscripts/firmware.ld
firmware/linkerscripts/firmware_memory.ld

The AMBE coder uses a block of ~8.5K In the middle of the lower 64K-SRAM for decoding and encoding. The space before and after is currently not used.
The .data section is now moved into the space before the AMBE RAM.
Heap (4KB) and stack (4KB) are moved to the space after the AMBE RAM.
This frees around 8.5K bytes in the upper 64K-SRAM.
This results in a memory usage of:
- upper SRAM: 64KB used ~41KB
- lower SRAM before AMBE: ~26.8KB used: 604B
- lower SRAM after AMBE: ~28.6KB used: 8KB
The compiler/linker positions all uninitialized variables into the .bss section in the upper SRAM and all initialized variables will get into the lower SRAM.
Moving a variable to a specific section is possible like this:
`BSS_LOWER_BOTTOM int var_in_lower_before_ambe_bss;`
`BSS_LOWER_TOP int …

Enable access to lower SRAM for data, heap and stack

---

firmware/source/user_interface/uiUtilityQSOData.c

Disable extended maidenhead code section.

---

firmware/include/user_interface/menuSystem.h
firmware/include/user_interface/uiUtilityQSOData.h
firmware/source/functions/fw_ticks.c
firmware/source/fw_main.c
firmware/source/user_interface/menuBattery.c
firmware/source/user_interface/menuLastHeard.c
firmware/source/user_interface/menuRSSIScreen.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiHotspot.c
firmware/source/user_interface/uiLockScreen.c
firmware/source/user_interface/uiPowerOff.c
firmware/source/user_interface/uiSplashScreen.c
firmware/source/user_interface/uiTxScreen.c
firmware/source/user_interface/uiTxTgPcContactOwnId.c
firmware/source/user_interface/uiUtilityQSOData.c
firmware/source/user_interface/uiVFOMode.c

If SK1 is pressed, extra infos + elapsed time are displayed, using 6x8* fonts.
TxScreen displays LH on SK1, but only centered callsign (just like normal LH screen).
Fix the damn fw_millis(): now it returns milliseconds. Rename uiEvent_t 'ticks' member to 'time'. Review all timediff checks (I hope I didn't missed one).
About LH (don't take care of elapsed time values)

[UPDATED] Fix timing (based on ticks) problems, fw_millis() returns ms. uiEvent ticks member renamed to time.

---

firmware/include/io/fw_keyboard.h
firmware/include/user_interface/menuSystem.h
firmware/include/user_interface/uiUtilityQSOData.h
firmware/source/fw_main.c
firmware/source/io/fw_keyboard.c
firmware/source/user_interface/menuLastHeard.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiTxScreen.c
firmware/source/user_interface/uiUtilityQSOData.c
firmware/source/user_interface/uiVFOMode.c

**BEWARE**: this revert the handling of SK1, as a button only. It've just disabled the button state checking statement in keyboard code, and replace all KEY_*(SK1) with old bitwise checking.
SK1 toggles the display view between normal  and details views (as in the other screen, ChannelMode, VFOMode).

New new Last Heard menu.

---

firmware/include/io/fw_keyboard.h
firmware/source/io/fw_keyboard.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiVFOMode.c

I removed all traces of including the handling of SK1 and ORANGE inside the keypad code.
This also removes the detection of long press buttons. If this is needed it has to be implemented inside fw_buttons.c

Complete remove buttons from keypad code, removes long press ORANGE

---

firmware/include/hardware/UC1701.h
firmware/source/fw_main.c
firmware/source/hardware/UC1701.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiUtilities.c
firmware/source/user_interface/uiVFOMode.c

Add ucClearRows(), I will replace all calls to ucFillRect() used to clear regions (memset is faster).

May prevent the blank screen when TG and PC are zero.

---

firmware/source/user_interface/uiHotspot.c

Use benefits from latest lastheard / cache updates.

HS: Minimalize contact lookups (only dmrIDs on RF RXing).

---

firmware/include/user_interface/uiUtilities.h

it will use more ram (already remapped to data.$RAM2), from 1792 to 3584 bytes.
16 entries could be a bit small if you're listening very active TG, and keeping contacts infos into the LH list a bit longer prevents lookups/TA processing.
Cheers.

Longer last heard list length (16->32 entries).

---

firmware/include/hardware/fw_HR-C6000.h
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiVFOMode.c

This fixes latency about contact informations rendering, when getting in and out of any menu when RXing (DIGITAL mode only).

Instant display contact info when getting out of a menu while RXing.

---

firmware/include/functions/fw_settings.h
firmware/include/user_interface/uiUtilities.h
firmware/source/functions/fw_settings.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiUtilities.c
firmware/source/user_interface/uiVFOMode.c

This patch makes it so that in Analog mode, both in VFO and Channel modes, the quick menu Filter setting allows selecting `CTCSS` (default) or `None`. When the filter is set to `None` the Rx CTCSS filter is disabled.
`STORAGE_MAGIC_NUMBER` is also bumped because the setting is added to the `nonVolatileSettings` struct.
I tested every scenario I could think of against another radio sending and not sending the access tone. I also cleaned up the code just a bit but only where I was touching it anyway and not in any dramatic way.
The feature looks like this:
I've also attached a test firmware based on 893c04f246dbaa5a3c7264fc07ff01bed560df02 (master when I rebased).
[OpenGD77-KC7RBW-analog-filter-setting-b0477f8.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/4247839/OpenGD77-KC7RBW …

Allow disabling Analog CTCSS filtering

---

firmware/source/functions/fw_settings.c
firmware/source/hardware/fw_HR-C6000.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiVFOMode.c

This method detects the received CC and then programs the HR-C6000 to receive that CC. Top line of display is updated and pressing Tx will return on the detected CC.
Not written back to the codeplug so changing channel will revert to programmed value for CC.

Alternative method of CC Filter disable.

---

.gitignore
firmware/include/main.h
firmware/include/user_interface/menuSystem.h
firmware/source/hardware/HR-C6000.c
firmware/source/hotspot/uiHotspot.c
firmware/source/main.c
firmware/source/user_interface/uiPowerOff.c

Hi Roger,
Hotspot overrides the DMR filter level (to CC+TS).
Implement fw_powerOffFinalStage() which restore latest overriden TG and restore DMR filter overriden by Hotspot mode (if modified), save the settings, then power off the MCU.
This is used in case of low battery and normal power off cycling.
Cheers.
...
Daniel

Change: keep CC in hotspot mode (new version)

---

firmware/source/functions/settings.c
firmware/source/user_interface/menuDisplayOptions.c

Make 14 default contrast value for the DM-1801. I tried to use the same value for both model, but it doesn't look similar here.

Reduce min contrast value from 12 to 5 (still slightly visible).

---

firmware/source/user_interface/uiVFOMode.c

Display scanning direction arrow between Lo/Hi QRGs. Make scan freq bounds entering a little more self-explanatory.
Add blinking cursor under current digit while entering frequency (VFO and Scan)
the cursor is smaller than in this picture (see the next one).

Scan qrg display

---

firmware/source/main.c

DM-1801's EEPROM looks slower than on the GD, so pulling the plug too early cause settings reset. So, I've introduce a grace time before setting auto-power's pin to LOW.

Avoid settings corruption (then reset) on DM-1801.

---

firmware/source/hotspot/uiHotspot.c

This prevent the HS to exit, as it seems MMDVMHost takes more time to initialize with recent changes (probably new NXDN stuff related, I need to confirm this).

Increase MMDVMHost timeout value.

---

firmware/source/functions/trx.c

Corrects the operation of receive CTCSS.
It was incorrectly being affected by the squelch setting.

Correct CTCSS Audio Amp Logic.

---

firmware/include/user_interface/menuSystem.h
firmware/source/hotspot/uiHotspot.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiTxScreen.c

We can't use the green one, its state is driven realtime in trx.c.

GD-77S: Add some kind of heartbeat notifications (3 quick flash each 5 secs).

---

firmware/source/io/display.c

As it was checking if backlight value was different from zero, but since the introduction of brightnessOff percentage, it was buggy (in BACKLIGHT_MODE_MANUAL).

Fix fw_displayIsBacklightLit() function.

---

firmware/include/functions/codeplug.h
firmware/source/functions/codeplug.c
firmware/source/functions/trx.c
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiUtilities.c

DCS values in the codeplug have the high bit set, which is something
that never happens with valid CTCSS codes. Since the DCS feature is not
yet ready to merge, ignore DCS values in the codeplug.
See [bug confirmed on the forum](https://opengd77.com/viewtopic.php?f=15&t=425&p=7249#p7249).
Also fixed a quasi-related bug where CTCSS wasn't configured correctly when switching radio modes from digital to analog using Blue+Star.

Ignore DCS

---

firmware/source/functions/trx.c

Fix problem where spurious CTCSS decodes were causing audio to briefly unmute.
Now needs Carrier Squelch AND CTCSS before audio Unmutes.

Add Carrier Squelch to CTCSS Logic

---

firmware/include/functions/settings.h
firmware/source/user_interface/menuBattery.c
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/menuDisplayMenuList.c
firmware/source/user_interface/menuDisplayOptions.c
firmware/source/user_interface/menuFirmwareInfoScreen.c
firmware/source/user_interface/menuLanguage.c
firmware/source/user_interface/menuOptions.c
firmware/source/user_interface/menuRSSIScreen.c
firmware/source/user_interface/menuSoundOptions.c
firmware/source/user_interface/menuZoneList.c
firmware/source/user_interface/uiLockScreen.c
firmware/source/user_interface/uiPrivateCall.c
firmware/source/user_interface/uiTxTgPcContactOwnId.c

Triggering light at the beginning of the event handler is way better than in the end (sometimes not reached).
setting.h: surround macro with do {} while(0).
Give some fresh air to menuChannelDetails: spaceless code won't run faster, but make it hard to read sometimes ;-)

Avoid updateScreen()s when not needed.

---

firmware/source/functions/codeplug.c

Found this bug while working on the DCS feature. The firmware wasn't decoding (or encoding) the CTCSS tones for VFO (only for channels). So for example if the VFO was configured for a 77Hz tone, the radio would think it was configured for 190.4Hz.
A similar bug existed when saving the VFO to the EEPROM.
This commit fixes both.

Fix VFO CTCSS

---

firmware/include/functions/trx.h
firmware/source/functions/trx.c
firmware/source/hardware/AT1846S.c
firmware/source/user_interface/menuSoundOptions.c

Please note: adding more gain just trigger Larsen effect.
Fix a bug I've made in Sound Options, calling setMicGainDMR() instead of setMicGainFM()...

FM Mic gain: add more gain from 18 to 31 (2 .. 15 on option screen).

---

firmware/source/user_interface/menuFirmwareInfoScreen.c

Just saw that on the public FB page (I don't have FB account, I couldn't ask how it was compiled, but the code is wrong anyway).

Cut GITVERSION at 7th char, not the bracket.

---

firmware/include/functions/settings.h
firmware/include/functions/vox.h
firmware/include/main.h
firmware/include/user_interface/uiLocalisation.h
firmware/source/functions/settings.c
firmware/source/functions/vox.c
firmware/source/hotspot/uiHotspot.c
firmware/source/main.c
firmware/source/user_interface/languages/catalan.h
firmware/source/user_interface/languages/czech.h
firmware/source/user_interface/languages/danish.h
firmware/source/user_interface/languages/english.h
firmware/source/user_interface/languages/finnish.h
firmware/source/user_interface/languages/french.h
firmware/source/user_interface/languages/german.h
firmware/source/user_interface/languages/italian.h
firmware/source/user_interface/languages/polish.h
firmware/source/user_interface/languages/portuguese.h
firmware/source/user_interface/languages/spanish.h
firmware/source/user_interface/languages/turkish.h
firmware/source/user_interface/menuSoundOptions.c
firmware/source/user_interface/uiSplashScreen.c
firmware/source/user_interface/uiTxScreen.c
firmware/source/user_interface/uiVFOMode.c

I didn't try on the 1801 yet.
Here, a Threshold of 3..4 looks fine.
The code avoid using 1, as it's way too low, and just trigger the vox all the time.
So, except for threshold value of zero (which turn the vox feature off), all other values are what is on option screen + 1, internally.
I set a default tail value of 2 seconds, as it looks fine. The tail values are units of 0.5 seconds.

Add simple VOX support, see "Sounds options".

---

firmware/source/functions/vox.c
firmware/source/hotspot/uiHotspot.c
firmware/source/user_interface/uiUtilities.c

HS: revert to previous version, removing vox enable/disable code.
HS Mode: write mode in bold even on analog mode.

VOX: take care of the hotspot running status.

---

firmware/source/main.c
firmware/source/usb/usb_com.c

Turn off the backlight while powering off, mostly related when low battery is triggered, as backlight will remains on until user action.

Wait 50ms before rebooting after the CPS has finished to write (related to EEPROM slowliness)

---

firmware/include/io/buttons.h
firmware/include/io/keyboard.h
firmware/include/io/rotary_switch.h
firmware/source/io/buttons.c
firmware/source/io/keyboard.c
firmware/source/io/rotary_switch.c
firmware/source/main.c
firmware/source/user_interface/menuContactList.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiVFOMode.c

Yes, it can bootup txing, but at least the feature is usable on that platform.
Maybe later we can use keypad too (without longpress/repeat).
**EDIT**: I changed the default shortcut to SK2 + UP + DOWN, as it works on all platform exceot the GD-77S.
On this one, I left SK2 + ORANGE, as the choice is quite limited.

Fix RD-5R custom content erase

---

firmware/source/user_interface/menuChannelDetails.c

**BUG?** RX/TX CTCSS looks twisted in the option screen, I've fixed this, but maybe I'm wrong for unknown reason.

Add longlong press to reach begin/end of CTCSS tones array.

---

firmware/include/io/keyboard.h
firmware/include/user_interface/menuSystem.h
firmware/source/main.c
firmware/source/user_interface/menuOptions.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/menuZoneList.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiVFOMode.c

ChannelMode:
- Fix SK2 + UP/DOWN. It does now handle repeat on zone selection.
- Can use DOWN to scroll down on repeat. Can't use UP as it start scanning (by design).
- Fix nuisance crashbug when all channel of the zone are part of the nuisance array (it just stop scanning when this condition is reached)
Options: don't let the key repeat < 1, as key repeat will trigger the watchdog.
main:
- full reindentation, sorry, was messy.
- don't play beeps when scanning is running, in both Channel and VFO modes.

Various keyboard fixes + 1 crash bug fix

---

firmware/source/user_interface/uiUtilities.c

While working on other things I noticed that the timeslot and ctcss indicators were not in the same position, nor did they have the same border size when filtering was disabled. The mode (FM / DMR) indicator was also not in the same position (FM being one pixel to the left of DMR). This commit fixes the positions and makes them easy to change together if you prefer they be a little further to the left.
This puts them about centered between FMN or DMR and 750mW.

Adjust TS1 / CTR indicator position

---

firmware/source/user_interface/menuDisplayOptions.c

Due to recent change in displaySetBacklightIntensityPercentage(), the backlight was turned completely off when toggling display's invert mode (firing displayInit()).
Thanks to IK0NWG for the bug report on the forum.

Fix backlight OFF when toggling Invert.

---

firmware/include/user_interface/uiUtilities.h
firmware/source/main.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiVFOMode.c

Also introduce LONGPRESS_REPEAT, just like in Channel mode (DOWN repeat, etc).
Don't let switching RX/TX input focus while freq scan is active.

VFO mode: fix scan (tone/freq) and SK buttons (+ PTT, etc).

---

firmware/include/functions/codeplug.h
firmware/source/functions/codeplug.c
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/uiChannelMode.c

Fix for #357 
There is an extra array of 76 bytes in the codeplug which determines if a rx group is valid.
Deleting a rx group in the cps does not clear the name. It removes all TGs from the group entry and sets the associated value in above array to 0.

Fix rxgroup list

---

firmware/include/functions/calibration.h
firmware/source/functions/calibration.c
firmware/source/functions/trx.c
firmware/source/main.c

* Use a structure instead of a byte array, this structure is derivated from the one used in CPS, with few modifications. It it get merged, I will backport it to the CPS.
* Implement a single function to retrieve calibration values.

Calibration rework.

---

firmware/include/interfaces/pit.h
firmware/include/io/buttons.h
firmware/include/user_interface/menuSystem.h
firmware/source/functions/speech_synthesis.c
firmware/source/interfaces/pit.c
firmware/source/io/buttons.c
firmware/source/main.c
firmware/source/user_interface/uiChannelMode.c

+ Have access to battery level in settings mode.
+ Announce timeslot: after ID_CODE xxxx KEY 1/2.
+ Group GD77S parameters into a struct.
+ Add long press state to SK1 and SK2 (ORANGE was already supported).
* We can operate the GD77S, even in settings mode.
New key assignments:
* **SK1**: channel announce,
* **SK1 Long**: "**+**" in settings,
* **SK2**: instant channel setting on RX (like on the other platforms),
* **SK2 Long**: "**-**" in settings.
Booleans to bitfield replacement has been pushed.

Permit to stay in settings mode on PTT and Rotary events.

---

firmware/source/user_interface/menuBattery.c
firmware/source/user_interface/menuFirmwareInfoScreen.c

Change KEYCHECK_PRESS to KEYCHECK_SHORTUP for GREEN in RED in battery and FWinfo menus.

Fix RED and GREEN in FWinfo and Battery menus.

---

firmware/include/user_interface/menuSystem.h
firmware/source/hotspot/uiHotspot.c
firmware/source/main.c
firmware/source/user_interface/menuBattery.c
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/menuContactDetails.c
firmware/source/user_interface/menuContactList.c
firmware/source/user_interface/menuCredits.c
firmware/source/user_interface/menuDisplayMenuList.c
firmware/source/user_interface/menuDisplayOptions.c
firmware/source/user_interface/menuFirmwareInfoScreen.c
firmware/source/user_interface/menuLanguage.c
firmware/source/user_interface/menuLastHeard.c
firmware/source/user_interface/menuOptions.c
firmware/source/user_interface/menuRSSIScreen.c
firmware/source/user_interface/menuSoundOptions.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/menuZoneList.c
firmware/source/user_interface/uiCPS.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiLockScreen.c
firmware/source/user_interface/uiPowerOff.c
firmware/source/user_interface/uiPrivateCall.c
firmware/source/user_interface/uiSplashScreen.c
firmware/source/user_interface/uiTxScreen.c
firmware/source/user_interface/uiTxTgPcContactOwnId.c
firmware/source/user_interface/uiVFOMode.c

Special beeps to every list + special beep for TG/PC/DMRId inputs.
Fix beep and SK2+Function.
Reset beep sound to default if we are scanning, otherwise the AudioAssist one could be played instead.
Add FIRST beep when VFO A is selected.
Handle key repeat.

Extend AudioAssist

---

firmware/include/io/buttons.h
firmware/include/user_interface/menuSystem.h
firmware/source/interfaces/pit.c
firmware/source/io/buttons.c
firmware/source/main.c
firmware/source/user_interface/menuBattery.c
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/menuContactDetails.c
firmware/source/user_interface/menuLastHeard.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiLockScreen.c
firmware/source/user_interface/uiTxScreen.c
firmware/source/user_interface/uiTxTgPcContactOwnId.c
firmware/source/user_interface/uiVFOMode.c

Use **BUTTONCHECK_SHORTUP**(uiEvent_t *, BUTTON_{SK,ORANGE}) | **BUTTONCHECK_LONGDOWN**(uiEvent_t *, BUTTON_{SK,ORANGE}) for key like behaviour.
Use **BUTTONCHECK_DOWN**(uiEvent_t *, BUTTON_{SK,ORANGE}) to check the button status when a keypad key is pressed.
Enable ORANGE short/long press on all platforms, except RD-5R.
I have enabled "BeepAssist" when VOICE is ON.
RD-5R not tested (but it compiles).

Re-introduce button short/long press.

---

Linux/etc/udev/rules.d/Fedora/readme.txt

When played with OH1FSS Python CPS r/w I would out that in CPS mode the symlinking does not work (Fedora 30).
SUBSYSTEM must be changed from usb to tty.  I think also MODE==666 is not needed as CPS r/w worked ok without it.

Rule change

---

firmware/source/functions/voicePrompts.c

If voice prompts data are missing, just reset the beep level if selected mode is one of the voice levels.

Fix not sticky no beep audio setting.

---

firmware/include/functions/codeplug.h
firmware/include/functions/trx.h
firmware/include/user_interface/uiUtilities.h
firmware/source/functions/codeplug.c
firmware/source/functions/trx.c
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/uiUtilities.c
firmware/source/user_interface/uiVFOMode.c

Implemented in display strings, channel details, and tone scanning.
Inverted DCS is really just DCS with mark and space in the data stream
inverted. It can be important to have this because older implementations
didn't agree on the meaning of mark and space, so some radios or
repeaters could call normal inverted and vice versa.
Because of how the math works out, inverted codes can be expressed as
non-standard codes. This also means that some non-standard codes are
actually inverted normal codes.
[OpenGD77-ajorg-dcs-inverted-20200704.zip](https://github.com/rogerclarkmelbourne/OpenGD77/files/4874202/OpenGD77-ajorg-dcs-inverted-20200704.zip)

DCS Inverted

---

firmware/source/user_interface/uiChannelMode.c

This bug was introduced with beep/voice assist feature. The beep has to be "manually" set, as no automatic beeps are allowed while scanning (and now the beep are set **after** the events processing)
Of course, there is no more two beeps when scan is starting, as the shortpress event happens only on release release now.
the voice prompts is also fixed when scanning
`It doesn't load the prompt **anymore** when it's scanning, but it does on pause or stop. If prompt level 3, channel is announced on pause or stop.`

Fix Channel mode longpress UP (startscan) missing beep + voice prompts

---

firmware/include/hardware/UC1701.h
firmware/include/user_interface/uiUtilities.h
firmware/source/hardware/UC1701.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiUtilities.c
firmware/source/user_interface/uiVFOMode.c

Turn many "extern const int" into #defines, as GCC won't handle them as real const unless there declared in the C file (there is constexpr in C++).
Add some safety in printSplitOrSpanText().
Remove and merge many platform conditional code about contact displaying.
Fix freq input for normal and VFO scanning + directional arrow (scanning direction) for RD-5R

[All Platforms] Fix displaying glitches

---

firmware/include/user_interface/uiUtilities.h
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiVFOMode.c

displaySquelch variable is shared and need to be reset when loading the menu, otherwise region could be cleared when switching between VFO and Channel menus, clearing the contact area (partially). 
Use ucClearRows() as it's possible and faster.

Fix rd5r (and other platforms) squelch area clearing

---

tools/font_tools/font_converter/Makefile

Turn off restrict warning (needed for GCC 9.x, as code is a bit "ugly" sometimes).

Fix font_tool compilation with GCC 9

---

firmware/source/user_interface/uiChannelMode.c

Fix of the incomplete channel setup after manual switch of the channel mode between analog and digital. Especially for the digital mode, a lot of properties (CC, TS, RxGroup..) were not set up and some subsequent manipulation (like a short PTT press) was neccessary to fix it.

Bugfix chanmode switch

---

firmware/source/user_interface/menuDisplayOptions.c

To reproduce, set min backlight value equal to backlight value, toggle invert: backlight off, and won't lit until reboot.
Because there is no other way to detect if the backlight is on, the PWM value is compared to displayBacklightPercentageOff.
So, minimum backlight need to be < to backlight value (and this is logical anyway).
(noticed that bug in a recent videoo on YT)

fix backlight stuck to off when toggling screen invert.

---

firmware/source/user_interface/menuDisplayOptions.c

Now the min backlight value is aligned to backlight - one (BACKLIGHT_PERCENTAGE_STEP_SMALL or BACKLIGHT_PERCENTAGE_STEP)
;-)

Align minimum value to backlight steps.

---

firmware/include/io/keyboard.h
firmware/source/io/keyboard.c
firmware/source/main.c
firmware/source/user_interface/uiTxScreen.c

Tested on GD-77, DM-1801 and RD-5R.

Fix 1750 and DTMF keys when PTT Latch is used (ANALOG only).

---

firmware/source/functions/trx.c

Based on #670 by Riku / OH1E and should help the following:
https://www.opengd77.com/viewtopic.php?f=11&t=1179
https://www.opengd77.com/viewtopic.php?f=11&t=794&start=40
I tested using three radios, one with DCS Tx setting, another with no Tx
tone or code, and the GD-77 with this patch receiving. With this patch
the receiving radio will receive if there's a clean DCS signal from the
one radio, and will hold the Rx open just a bit if the signal is doubled
by the second radio or if the first (DCS Tx) radio stops transmitting
but the second is still transmitting. It stops immediately if the signal
is lost.
I don't have any idea if 100 is a good number of measurements to
overcome the observed problems or if it's excessive, but the number can
be tweaked if people who are seeing those problems …

Tolerate some loss of CTCSS / DCS in Rx

---

firmware/include/user_interface/uiUtilities.h
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/menuSystem.c
firmware/source/user_interface/uiUtilities.c

changes by VK7JS Joseph 9 Sept 2020
1. left and right arrow now read the character moved to when editing a channel name.
2. sk2+left (backspace) now reads the character being deleted.
3. As user presses alphanumeric keys during text entry, the preview character is spoken along with the final character entered.
4. The channel name field is no longer repeated each time a key is pressed during channel name editing.

Improved editing of channel name with voice prompts.

---

firmware/include/functions/voicePrompts.h
firmware/include/user_interface/uiUtilities.h
firmware/source/dmr_codec/codec.c
firmware/source/functions/trx.c
firmware/source/functions/voicePrompts.c
firmware/source/hardware/HR-C6000.c
firmware/source/main.c
firmware/source/user_interface/menuChannelDetails.c
firmware/source/user_interface/menuLastHeard.c
firmware/source/user_interface/uiChannelMode.c
firmware/source/user_interface/uiTxTgPcContactOwnId.c
firmware/source/user_interface/uiUtilities.c
firmware/source/user_interface/uiVFOMode.c

Since announce*() functions are declared static, a special case for the GD77S has be handled.
All these functions loose their static attribute when compiled for GD77S platform.

Fix compilation for the GD77S.

---

tools/Python/FirmwareLoader/gd-77_firmware_loader.py
tools/Python/ScreenGrabber/gd-77_screen_grabber.py

Remove Python3 version checking and specific Python2 code.
Add correct exit code.

Drop Python2, as it's EOL, plus, some modules aren't available anymore.

---

firmware/source/user_interface/menuLastHeard.c

Fixed the behavior of voicing the Last Heard items, where only follow-on browsing was possible. Once the announcement was terminated, the browsing wasn't voiced until SK1 was pressed to activate the voice again.
Besides, a little of redundant code has been removed.

Improved Last Heard responsivity with voice prompts

---

firmware/source/user_interface/uiUtilities.c

These memcpy() copies extra bytes, the last byte is overwritten by buffer[16]=0.
Maybe this should be 16 not 17.

revise memcpy(buffer, text, size); and buffer[size]='\0' pair

---

firmware/Makefile

To build without modifying Makefile for other (not GD77) radioes,
RADIO variable is added. Build like this;
make -f ../Makefile -j8 RADIO=GD77s
This variable reflects the option of bin2sgl.

specify RADIO type for Makefile
