rogerclarkmelbourne/OpenGD77

firmware/source/menu/menuChannelMode.c
=> Change zone in channel mode using sk2 + up/down keys.

firmware/include/functions/fw_codeplug.h, firmware/include/functions/fw_trx.h, firmware/source/functions/fw_codeplug.c
Solves compiler warning for trxUpdateTsForCurrentChannelWithSpecifiedContact()
=> Fix circular dependency #38

firmware/source/user_interface/menuBattery.c
Here is a new battery icon.
... sorry for the blurry picture ;-) ...
=> New battery icon.

firmware/include/io/fw_keyboard.h, firmware/include/usb/fw_usb_com.h, firmware/include/user_interface/menuSystem.h, firmware/source/fw_main.c, firmware/source/io/fw_keyboard.c, firmware/source/usb/fw_usb_com.c, firmware/source/user_interface/menuDisplayMenuList.c, firmware/source/user_interface/menuSystem.c, firmware/source/user_interface/menuUtilityQSOData.c, firmware/source/user_interface/uiLockScreen.c
In the main menu pressing star locks keypad.
Unlocking with green key followed by star. #43
PTT will not be locked.
=> Add keylock with key star in main menu

firmware/source/hardware/UC1701.c
I think it's better, and more traceable.
=> Replace out of bound char by a question mark instead of ignoring them.

firmware/source/functions/fw_codeplug.c
Another leftover from extending frequencies and enable 6.25kHz step. Issue #89
=> Fixes copy frequencies from VFO to codeplug.

firmware/source/user_interface/uiTxTgPcContactOwnId.c
It also supports UP/DOWN key now.
=> Fix ID entry, if a 7th digit was entered, it wasn't possible to delete anymore.

firmware/include/hardware/UC1701.h, firmware/source/hardware/UC1701.c, firmware/source/user_interface/menuContactDetails.c, firmware/source/user_interface/menuContactList.c, firmware/source/user_interface/uiUtilityQSOData.c
Instead of cheating printCentered() ;-)
=> Adds UC1701_drawChoice() that displays choices above GREEN and RED buttons

firmware/source/functions/fw_trx.c, firmware/source/fw_main.c, firmware/source/hardware/fw_HR-C6000.c, firmware/source/user_interface/menuContactList.c, firmware/source/user_interface/menuCredits.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiVFOMode.c
Last pass, I think I didn't forget one.
About the build, since some guys on the forum wants to build their own, I think it's a good measure to not let them build Release targets, as it don't work (yet). I'm talking from personnal experience ;-)
=> Last (forgotten) implicit void missing argments. Make a non debug build to fail, as it won't work

firmware/source/user_interface/uiChannelMode.c
Two more places with old key handling.
=> Handle keys UP and DOWN with new key handling while in scanning mode.

firmware/source/io/fw_keyboard.c
Fix for power on and occasionally keypad lock. (#153)
=> Changed keypad debounce to fix keypad lock.

firmware/include/user_interface/uiLocalisation.h, firmware/source/user_interface/languages/danish.h, firmware/source/user_interface/languages/finnish.h, firmware/source/user_interface/uiLocalisation.c
=> Import (with fixes) Finnish language from Riku (is that a call ? ;-) ). Some strings are still too long.

firmware/source/io/fw_keyboard.c
arrg, forgotten flag for up after long detection
=> fix keypad long press detection

firmware/include/user_interface/menuSystem.h, firmware/source/fw_main.c, firmware/source/io/fw_keyboard.c, firmware/source/user_interface/menuSystem.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiTxScreen.c, firmware/source/user_interface/uiVFOMode.c
=> Sk2 override keylock 2

firmware/source/user_interface/languages/catalan.h
All Channel, Battery and Scan messages translated/fixed.
All Channel was too long, allowing only ONE digit to be shown.  Now there's room for 5 digits. ;)
=> All Channel, Battery and Scan messages

firmware/source/user_interface/languages/catalan.h
Yes, there were missing accents.  Fully fixed now.
Notepad++ ANSI.
=> Yes, there were missing accents.  Fully fixed now.

firmware/source/user_interface/uiUtilityQSOData.c
=> Thicker (by 1px, top) reverse video TS background.

firmware/source/user_interface/uiTxScreen.c
(I can't reproduce it here, and I've huge ADSL problems ATM, can't even use my hotspot).
=> Possible fix for TX screen lockup

firmware/source/user_interface/menuBattery.c
This bug was introduced when I make it stop refreshing for nothing.
Cheers.
=> Force redraw if battery level < 15%, blinking the level.

firmware/include/functions/fw_settings.h, firmware/include/io/fw_display.h, firmware/include/user_interface/uiLocalisation.h, firmware/source/functions/fw_settings.c, firmware/source/fw_main.c, firmware/source/io/fw_display.c, firmware/source/user_interface/languages/catalan.h, firmware/source/user_interface/languages/danish.h, firmware/source/user_interface/languages/english.h, firmware/source/user_interface/languages/finnish.h, firmware/source/user_interface/languages/french.h, firmware/source/user_interface/languages/german.h, firmware/source/user_interface/languages/italian.h, firmware/source/user_interface/languages/polish.h, firmware/source/user_interface/languages/portuguese.h, firmware/source/user_interface/languages/spanish.h, firmware/source/user_interface/menuDisplayOptions.c, firmware/source/user_interface/menuSystem.c
Since SK1 is the obvious button to press in auto mode to trigger the backlight, I chose it also as toggle button in Manual mode.
#80
=> Implement backlight modes Auto/Manual/None.

firmware/include/functions/fw_settings.h, firmware/include/user_interface/uiLocalisation.h, firmware/source/functions/fw_settings.c, firmware/source/fw_main.c, firmware/source/user_interface/languages/catalan.h, firmware/source/user_interface/languages/danish.h, firmware/source/user_interface/languages/english.h, firmware/source/user_interface/languages/finnish.h, firmware/source/user_interface/languages/french.h, firmware/source/user_interface/languages/german.h, firmware/source/user_interface/languages/italian.h, firmware/source/user_interface/languages/polish.h, firmware/source/user_interface/languages/portuguese.h, firmware/source/user_interface/languages/spanish.h, firmware/source/user_interface/menuOptions.c, firmware/source/user_interface/uiTxScreen.c
It will work only if TOT is set. Any button/key event will cancel xmitting.
Fix TIMEOUT error message (was invisible due to new event stuff).
=> Implement PTT toggle behavior.

firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiVFOMode.c
Add SK1 support in VFOMode, it displays CTCSS and squelch in analog.
=> In ChannelMode, display TG line when pressing SK1 (in RX).

firmware/source/hardware/fw_HR-C6000.c
Change timecode to toggle every Timeslot Interrupt and re-sync only after seeing three differences with CACH value.
Seems to improve selection of correct timeslot by ignoring glitches in CACH value.
Still uses CACH value directly during repeater wakeup.
=> Changes to timeCode

firmware/include/user_interface/uiUtilityQSOData.h, firmware/source/user_interface/uiUtilityQSOData.c
Lookup receiving TG in contacts.
=> Get name of receiving TG if in stored in contacts.

firmware/source/user_interface/menuDisplayOptions.c, firmware/source/user_interface/menuSystem.c
Fixed backlight percentage value changes not dynamic while in manual mode.
=> Make backlight mode/timeout changes realtime.

firmware/source/user_interface/uiHotspot.c
There is small changes, MMDVMHost related + HS FW display on SK1.
I'm waiting for the reports about BlueDV problems.
=> Hotspot fine tunning

firmware/source/user_interface/menuContactDetails.c
I broke that in one of my earlier PRs.
=> Fix entry of TG or ID in contact details

firmware/source/fw_main.c
=> Small HS test fix.

firmware/include/functions/fw_settings.h, firmware/source/functions/fw_settings.c, firmware/source/user_interface/uiVFOMode.c
VFO Scanning.
Has been tested by several people and appears to be stable.
=> Add VFO Scanning

firmware/source/user_interface/uiUtilityQSOData.c
Another one some people liked, but I'm not sure if you will. Close it if you don't like it ;-)
=> Add notifier (DMR in bold) when HS is enabled.

firmware/include/user_interface/uiLocalisation.h, firmware/source/fw_main.c, firmware/source/hardware/fw_HR-C6000.c, firmware/source/user_interface/languages/catalan.h, firmware/source/user_interface/languages/danish.h, firmware/source/user_interface/languages/english.h, firmware/source/user_interface/languages/finnish.h, firmware/source/user_interface/languages/french.h, firmware/source/user_interface/languages/german.h, firmware/source/user_interface/languages/italian.h, firmware/source/user_interface/languages/polish.h, firmware/source/user_interface/languages/portuguese.h, firmware/source/user_interface/languages/spanish.h, firmware/source/user_interface/menuOptions.c, firmware/source/user_interface/uiPrivateCall.c, firmware/source/user_interface/uiUtilities.c
Add new label to languages for setting 'private call handling'.
Remove blocking of ID id private call is declined.
Fix cut off of private call melody.
=> Private call fixes

firmware/source/user_interface/languages/catalan.h, firmware/source/user_interface/languages/danish.h, firmware/source/user_interface/languages/english.h, firmware/source/user_interface/languages/french.h, firmware/source/user_interface/languages/german.h, firmware/source/user_interface/languages/italian.h, firmware/source/user_interface/languages/polish.h, firmware/source/user_interface/languages/portuguese.h, firmware/source/user_interface/languages/spanish.h, firmware/source/user_interface/uiUtilities.c
Align this entry in all files.
uiUtilities.c: Fix typo in comment.
=> French translatation of .private_call_handling.

firmware/source/user_interface/uiHotspot.c
This permits to enable POCSAG support in Pi-Star to send and receive pages. Of course the GD-77 won't transmit POCSAG messages.
=> Handle POCSAG. 

firmware/source/user_interface/uiHotspot.c
That may fix first time keying, with new txdelay stuff.
=> Fix uninitialized tone, as TX delay was introduced.

firmware/source/user_interface/uiHotspot.c
=> HS fix: wrong contact info on screen

firmware/source/user_interface/uiHotspot.c
And reduce CW buffer (300 to 64)
=> HS: Display 'TX CW' while beaconning.

firmware/source/user_interface/uiChannelMode.c
Just to cleanup the quick fix.
=> No need to return that early.

firmware/include/functions/fw_settings.h, firmware/include/user_interface/uiLocalisation.h, firmware/include/user_interface/uiUtilities.h, firmware/source/functions/fw_settings.c, firmware/source/user_interface/languages/catalan.h, firmware/source/user_interface/languages/danish.h, firmware/source/user_interface/languages/english.h, firmware/source/user_interface/languages/finnish.h, firmware/source/user_interface/languages/french.h, firmware/source/user_interface/languages/german.h, firmware/source/user_interface/languages/italian.h, firmware/source/user_interface/languages/polish.h, firmware/source/user_interface/languages/portuguese.h, firmware/source/user_interface/languages/spanish.h, firmware/source/user_interface/menuOptions.c, firmware/source/user_interface/uiUtilities.c
This revert the latest changes about this topic.
ATM, I didn't set a translation for "Order" string. It's not the best choice anyway, but only 7 characters are free to define something.
Hope you will like it.
Cheers.
=> Contact lookup priority order between codeplug/DMRIDs and TA.

firmware/include/functions/fw_settings.h, firmware/include/user_interface/uiLocalisation.h, firmware/source/functions/fw_settings.c, firmware/source/user_interface/languages/catalan.h, firmware/source/user_interface/languages/danish.h, firmware/source/user_interface/languages/english.h, firmware/source/user_interface/languages/finnish.h, firmware/source/user_interface/languages/french.h, firmware/source/user_interface/languages/german.h, firmware/source/user_interface/languages/italian.h, firmware/source/user_interface/languages/polish.h, firmware/source/user_interface/languages/portuguese.h, firmware/source/user_interface/languages/spanish.h, firmware/source/user_interface/menuOptions.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiVFOMode.c
Add translation entry for stop (french updated + a little fix about 'Hold' translation).
Scan logic is untouched.
=> Add new Stop scan mode, to extend Hold and Pause (usefull to track an intermittent signal, somewhere).

firmware/include/functions/fw_settings.h, firmware/include/user_interface/uiLocalisation.h, firmware/source/functions/fw_settings.c, firmware/source/user_interface/languages/catalan.h, firmware/source/user_interface/languages/danish.h, firmware/source/user_interface/languages/english.h, firmware/source/user_interface/languages/finnish.h, firmware/source/user_interface/languages/french.h, firmware/source/user_interface/languages/german.h, firmware/source/user_interface/languages/italian.h, firmware/source/user_interface/languages/polish.h, firmware/source/user_interface/languages/portuguese.h, firmware/source/user_interface/languages/spanish.h, firmware/source/user_interface/menuOptions.c, firmware/source/user_interface/uiUtilities.c
About the LH item's contact on one line, I think an option is needed.
Cheers.
=> Get rid of 'DMR ID:' in TA, and don't split LH item->contact.

firmware/include/usb/fw_usb_com.h, firmware/source/usb/fw_usb_com.c, firmware/source/user_interface/uiHotspot.c
Thanks to KD2LH, Marc, for all the tests.
Increate USB TX buffer from 512 to 1024 bytes (but it's 4 bytes aligned...)
No more ghost frame.
Honor latest lookup/TA order option.
Ignore RF frames while in POCSAG.
Some code cleanup/indent.
Bump version to 0.1.0.
=> HS: latest fixes and enhancements.

firmware/source/user_interface/languages/catalan.h
Fixes done as per OpenGD7 forum
=> Fixes done as per OpenGD7 forum

tools/Python/FirmwareLoader/gd-77_firmware_loader.py
Tested under Linux (python 2.7 and 3.6) and Windows (python 2.7).
Cheers
...
Daniel
=> Probe for connected model. Check if the firmware that will be flashed matches the HT.

firmware/source/user_interface/uiChannelMode.c
Pressing SK1 + ORANGE enables reverse RX/TX (with visual feedback. Reverse will be hold until ORANGE is down (even if SK1 is released first, or pressed again).
=> Reintroduce SK1 for channel details.

firmware/source/hotspot/uiHotspot.c
That may fix some problems when hotspot has left then re-enter, but MMDVMHost hasn't restarted (configuration won't be sent again).
=> Set CC, QRG and output power when the hotspot mode is entering.

firmware/source/user_interface/uiVFOMode.c
Reorder switch/case to follow the menu enum.
Change sprintf format to align freq, avoiding CTCSS word moves while scanning.
=> Reintroduce tone scan in VFO quick menu.

firmware/source/hotspot/uiHotspot.c
Add some extra info send to MMDVMHost, about radio and HS type (could be useful for support).
=> GD-77S: Use the orange button to exit the hotspot mode (BlueDV only).

firmware/source/functions/speech_synthesis.c, firmware/source/user_interface/uiChannelMode.c
Hi Roger,
Okay, I fixed my mistake.
Also, maybe you didn't noticed but I shorted the corners about spelling things like this:
439.9875
It will be spelled:
four hundred thirty nine point nine hundred eighty seven FIVE
Cheers.
=> Fix hundreds spelling.

firmware/include/functions/settings.h, firmware/include/functions/trx.h, firmware/include/hardware/AT1846S.h, firmware/include/user_interface/uiLocalisation.h, firmware/source/functions/settings.c, firmware/source/functions/trx.c, firmware/source/hardware/AT1846S.c, firmware/source/user_interface/languages/catalan.h, firmware/source/user_interface/languages/czech.h, firmware/source/user_interface/languages/danish.h, firmware/source/user_interface/languages/english.h, firmware/source/user_interface/languages/finnish.h, firmware/source/user_interface/languages/french.h, firmware/source/user_interface/languages/german.h, firmware/source/user_interface/languages/italian.h, firmware/source/user_interface/languages/polish.h, firmware/source/user_interface/languages/portuguese.h, firmware/source/user_interface/languages/spanish.h, firmware/source/user_interface/languages/turkish.h, firmware/source/user_interface/menuSoundOptions.c
(in Sound options: -15 to 15) default is 1, all of my GD/MD are calibrated to 17, datasheet tells 16 might be the default.
There is no zero gain, as it turn mic OFF.
=> Add FM mic gain.

firmware/source/hardware/UC1701.c, firmware/source/hardware/UC1701_transfer.c, firmware/source/hotspot/uiHotspot.c, firmware/source/user_interface/menuBattery.c, firmware/source/user_interface/menuLastHeard.c, firmware/source/user_interface/menuRSSIScreen.c, firmware/source/user_interface/menuSystem.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiTxTgPcContactOwnId.c, firmware/source/user_interface/uiUtilities.c, firmware/source/user_interface/uiVFOMode.c
Some division by 2 replaced by bit shifting.
=> Use DISPLAY_SIZE_X instead of hardcoded pixel value + battery level fix.

firmware/include/io/display.h, firmware/source/functions/settings.c, firmware/source/io/display.c, firmware/source/main.c, firmware/source/user_interface/menuBattery.c, firmware/source/user_interface/menuContactList.c, firmware/source/user_interface/menuCredits.c, firmware/source/user_interface/menuDisplayOptions.c, firmware/source/user_interface/menuLastHeard.c, firmware/source/user_interface/menuRSSIScreen.c, firmware/source/user_interface/menuSystem.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiPrivateCall.c, firmware/source/user_interface/uiVFOMode.c
Fix some backlight problems, like keeping setting the PWM while it's not needed (while TXing). Now it's just doing it once when starting TXing.
=> Fix output frequency swipe

docs/OpenGD77_User_Guide.html, docs/OpenGD77_User_Guide.md
=> Fix GD-77S HS typos.

firmware/source/functions/vox.c, firmware/source/user_interface/uiTxScreen.c
uiTxScreen: prevent tx start beep to reset the vox.
=> Add noise floor support, threshold value is now above sampled noise.

firmware/include/functions/settings.h, firmware/source/functions/settings.c, firmware/source/main.c
Tested on my GD-77, now I need to reflash my codepug :-D
=> Add custom contain erase shortcut (SK2 + ORANGE)

firmware/source/user_interface/menuChannelDetails.c
- LEFT/RIGHT: as usual
- SK2 + LEFT/RIGHT: jumps to begin/end of each category, following this scheme
None .. CTCSS[0] .. CTCSS[max] .. DCS[0] .. DCS[max]
- LONGPRESS LEFT/RIGHT: increment/decrement with a step of 5.
Put RX CSS before TX CSS on screen, as it was before I fixed something else. Now it follows again the order in the firmware.
=> Implement easy navigation through sub-audible tones.

docs/OpenGD77_User_Guide.md, firmware/include/functions/codeplug.h, firmware/include/functions/trx.h, firmware/source/functions/codeplug.c, firmware/source/functions/settings.c, firmware/source/functions/trx.c, firmware/source/hotspot/uiHotspot.c, firmware/source/user_interface/menuChannelDetails.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiTxScreen.c, firmware/source/user_interface/uiUtilities.c, firmware/source/user_interface/uiVFOMode.c
I thought about re-basing this so that it had some discreet commits but ultimately decided that a squashed commit was a better starting place. I'm happy to break it up if someone wants that.
I'd also thought about cleaning everything up better, but when I took a look at what I had done so far it actually looked pretty good, so I wanted to get this PR up to get some feedback.
Notes about this are at https://hackmd.io/@ajorg/Bk5AR_8YU including two known issues and some TODOs.
Please let me know what needs to be changed before this can be merged.
=> Add DCS support

firmware/source/functions/settings.c
As STORAGE_MAGIC_NUMBER has been changed few times since then. Was introduced on Sep 7 2019.
=>  Remove beep related settings checkings.

firmware/source/user_interface/menuSystem.c, firmware/source/user_interface/uiUtilities.c
- fix edit cursor position
- fix two-line QSO information positioning
=> Visual fixes for RD-5R menus

firmware/include/user_interface/menuSystem.h, firmware/source/user_interface/menuChannelDetails.c, firmware/source/user_interface/menuContactDetails.c, firmware/source/user_interface/menuContactList.c, firmware/source/user_interface/menuDisplayMenuList.c, firmware/source/user_interface/menuDisplayOptions.c, firmware/source/user_interface/menuLanguage.c, firmware/source/user_interface/menuOptions.c, firmware/source/user_interface/menuSoundOptions.c, firmware/source/user_interface/menuSystem.c, firmware/source/user_interface/menuZoneList.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiVFOMode.c
Passing the variable as a pointer it better, and avoid (found missing) assignments.
=> Change menuSystemMenuIncrement() and menuSystemMenuDecrement() function prototypes.

firmware/include/functions/trx.h, firmware/include/user_interface/menuSystem.h, firmware/include/user_interface/uiUtilities.h, firmware/source/main.c, firmware/source/user_interface/menuChannelDetails.c, firmware/source/user_interface/uiVFOMode.c
Just found the tone scan was broken since the DCS was added.
Now CTCSS / DCS scan works.
=> Add dcs to tone scan

firmware/source/functions/settings.c, firmware/source/main.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiUtilities.c
Adds DMR TS_TG and TS DMR filters support (LEVEL MODE {ON,OFF}).
Adds scan mode (SK1: start/stop, SK2: nuisance/reverse scan direction).
=> GD77S: Invert SK1/SK2 long/short press events.

tools/Python/FirmwareLoader/gd-77_firmware_loader.py
Something definitely gone wrong. This was merged 14 days ago, but it not in the repo anymore. I think I will need to review the latest merges...
I just checked 25 days of PRs, it seems fine. So, two PRs disappeared for unknown reason/trace..
=> Fix GD-77S Python, again.

firmware/Makefile, firmware/linkerscripts/firmware_library_newlib.ld, firmware/linkerscripts/firmware_newlib.ld
Added the support to build with newlib instead of redlib.
I also added a makefile to build the project from Linux without the NXP IDE which supports both newlib and redlib
This should not break the redlib build from MCUXpresso however it is still not possible to compile with the newlib from the IDE
Closes #622
=> Add Newlib support

firmware/source/user_interface/uiVFOMode.c
We already have RT/TX QRG exchange, but it's a slow operation just for a quick check.
=> Add reverse repeater (SK1+SK2) in VFO mode.

firmware/include/functions/codeplug.h
based on what I read in CPS code
=> Document contact's TS override

firmware/include/user_interface/menuSystem.h, firmware/include/user_interface/uiUtilities.h, firmware/source/user_interface/menuContactList.c, firmware/source/user_interface/menuSystem.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiTxTgPcContactOwnId.c, firmware/source/user_interface/uiUtilities.c
From various contact picking lists (###, menu contact->list->select TX, SK2+#)
=> Apply contact TS override

tools/Python/ScreenGrabber/gd-77_screen_grabber.py
Switch to Python v3 (it's time to close the coffin, as most python library packages aren't available anymore).
=> Fix blury output on rescalling.

firmware/source/user_interface/uiChannelMode.c
=> If current contact in TG list is out of bounds, select first contact.

firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiVFOMode.c
Was stuck to channel informations.
=> Display QSO Information when switching contacts

firmware/source/user_interface/uiLockScreen.c
=> Add voice prompt to the lock screen.

docs/OpenGD77_User_Guide.md, docs/media/DM-1801-Cheatsheet-01.svg, docs/media/GD77-Cheatsheet-01.svg
Cleaned up commit
Four changes made to sections:
3 as per issue 696 and one image(svg) attached
Added doc in Installation about Transferring data
Added docs in OpenGD77 Menu re the boot tune as morse code
Added in same are re notes and melodies
Added cheatshet for DM1801 under the GD77 image
=> Issue 696 docupdates

firmware/source/user_interface/uiVFOMode.c
=> Fix silent point when setting upper VFO scan freq.

firmware/include/functions/codeplug.h, firmware/source/functions/codeplug.c, firmware/source/user_interface/menuContactDetails.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiTxTgPcContactOwnId.c, firmware/source/user_interface/uiVFOMode.c
Introduce and use CODEPLUG_CONTACTS_MIN/MAX constants.
Fix VFO -> New Channel: valid indexes were 1..1023, which was wrong.
=> Rework getNextContact().

firmware/include/user_interface/uiUtilities.h, firmware/source/user_interface/menuBattery.c, firmware/source/user_interface/menuChannelDetails.c, firmware/source/user_interface/menuContactDetails.c, firmware/source/user_interface/menuContactList.c, firmware/source/user_interface/menuCredits.c, firmware/source/user_interface/menuDisplayMenuList.c, firmware/source/user_interface/menuDisplayOptions.c, firmware/source/user_interface/menuFirmwareInfoScreen.c, firmware/source/user_interface/menuLanguage.c, firmware/source/user_interface/menuLastHeard.c, firmware/source/user_interface/menuOptions.c, firmware/source/user_interface/menuRSSIScreen.c, firmware/source/user_interface/menuSoundOptions.c, firmware/source/user_interface/menuZoneList.c, firmware/source/user_interface/uiChannelMode.c, firmware/source/user_interface/uiLockScreen.c, firmware/source/user_interface/uiTxTgPcContactOwnId.c, firmware/source/user_interface/uiUtilities.c, firmware/source/user_interface/uiVFOMode.c
Add/complete VP to contact list/new.
Remove audioPromptMode checkings when voicePrompts*() are used, as that level is checked into these functions also.
=> Implement and use repeatVoicePromptOnSK1();

docs/OpenGD77_User_Guide_CN.md
The CN PDF will remain as it is, as I can't generate a new one. Also, I tried the .md file locally, using "grip", but none of the anchor works.
=> Update Chinese doc after battery images renaming.

firmware/include/interfaces/hr-c6000_spi.h
=> Fix two GCC warnings (implicit declarations).
